
[aigc.agent]
max_retry = 3
max_iter = 5
max_parallel_subagents = 3

[aigc.api.chatcomp]
base = "http://localhost:8080/v1"
authkey = ""
model = ""
model_hasVision = true

[init.ignore]
ext = ["txt", "md", "html", "log", "py"]
folder = [".git", "__pycache__", "pennyparse_output", "pennyparse_results"]

[init.sampling]
by = "random"  # first, random, none
num = 3        # >=0
pdf_page = 3   # >=0
pdf_page_total_max = 20   # >=0

[reviewer]
max_length = 1000 # must be substantially less than LLM's context window

[output]
dir = "pennyparse_results"
ext = "auto"  # auto, txt, md, html
pdf_perpage_threshold = 5  # if pdf_pages <= $pdf_perpage_threshold, put extracted text in a single output file
parser_summary_batch = 5

[cli]
timeout = 15

[web]
host = "0.0.0.0"
port = 52026
